personal:
  git_email: jameskaupert@gmail.com
  git_name: "James Kaupert"

base_packages:
  packages:
    - ca-certificates
    - curl
    - linux-headers
    - git
    - openssh
    - xclip
    - pass
    - vi
    - vim

audio:
  packages:
    - pamixer
    - pavucontrol
    - pipewire-alsa
    - pipewire-pulse
    - wireplumber
    - bluez
    - bluez-utils

browsers:
  packages:
    - chromium

cli_tools:
  packages:
    - bat
    - btop
    - duf
    - dust
    - eza
    - fd
    - ffmpeg
    - fzf
    - github-cli
    - jq
    - neovim
    - ripgrep
    - tmux
    - unzip
    - wget

containers:
  packages:
    - podman
    - podman-docker
    - k9s

desktop:
  packages:
    - cage
    - cliphist
    - fuzzel
    - gnome-keyring
    - greetd
    - grim
    - libinput
    - mako
    - niri
    - nvidia-dkms
    - nvidia-utils
    - satty
    - slurp
    - xdg-desktop-portal-gnome
    - xdg-desktop-portal-gtk
    - xwayland-satellite
    - wayland
    - waybar
    - wl-clipboard
    - wlsunset

fonts:
  packages:
    - otf-font-awesome
    - otf-overpass-nerd
    - noto-fonts
    - noto-fonts-emoji
    - ttf-cascadia-code-nerd
    - ttf-dejavu
    - ttf-go-nerd
    - ttf-iosevka-nerd
    - ttf-jetbrains-mono-nerd
    - ttf-liberation
    - woff2-font-awesome

gui_tools:
  packages:
    - calibre
    - okular
    - pdfarranger
    - steam
    - lib32-nvidia-utils

  appimages:
    localsend:
      name: LocalSend
      appimage_path: "{{ package_management.appimage_path }}/LocalSend.AppImage"
      desktop_entry_path: "{{ package_management.desktop_entry_path }}/localsend.desktop"
      url: https://github.com/localsend/localsend/releases/download/v1.17.0/LocalSend-1.17.0-linux-x86-64.AppImage

    obsidian:
      name: Obsidian
      appimage_path: "{{ package_management.appimage_path }}/Obsidian.AppImage"
      desktop_entry_path: "{{ package_management.desktop_entry_path }}/obsidian.desktop"
      url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.10.6/Obsidian-1.10.6.AppImage

    cursor_ai:
      name: CursorAI
      appimage_path: "{{ package_management.appimage_path }}/CursorAI.AppImage"
      desktop_entry_path: "{{ package_management.desktop_entry_path }}/cursor_ai.desktop"
      url: https://api2.cursor.sh/updates/download/golden/linux-x64/cursor/2.3

package_management:
  packages:
    - base-devel
    - fuse2
    - fuse-overlayfs
  appimage_path: "{{ ansible_facts['env']['HOME'] }}/.local/bin"
  desktop_entry_path: "{{ ansible_facts['env']['HOME'] }}/.local/share/applications"

terminals:
  packages:
    - alacritty

workspace:
  path: $HOME/workspace/github.com/jameskaupert
