personal:
  git_email: jameskaupert@gmail.com
  git_name: "James Kaupert"

base_packages:
  - ca-certificates
  - curl
  - linux-headers
  - git
  - openssh
  - xclip
  - pass

audio:
  - pamixer
  - pavucontrol
  - pipewire-alsa
  - pipewire-pulse
  - wireplumber
  - bluez
  - bluez-utils

browsers:
  - chromium

cli_tools:
  - bat
  - btop
  - duf
  - dust
  - eza
  - fd
  - ffmpeg
  - fzf
  - github-cli
  - jq
  - neovim
  - ripgrep
  - tmux
  - unzip
  - wget

containers:
  - docker
  - docker-compose
  - fuse2

desktop:
  - fuzzel
  - gnome-keyring
  - libinput
  - niri
  - nvidia-dkms
  - nvidia-utils
  - xdg-desktop-portal-gnome
  - xdg-desktop-portal-gtk
  - xwayland-satellite
  - wayland
  - waybar

fonts:
  - otf-font-awesome
  - otf-overpass-nerd
  - noto-fonts
  - noto-fonts-emoji
  - ttf-cascadia-code-nerd
  - ttf-dejavu
  - ttf-go-nerd
  - ttf-iosevka-nerd
  - ttf-jetbrains-mono-nerd
  - ttf-liberation
  - woff2-font-awesome

gui_tools:
  packages:
    - okular
  appimages:
    localsend:
      name: LocalSend
      appimage_path: "{{ package_management.appimage_path }}/LocalSend.AppImage"
      desktop_entry_path: "{{ package_management.desktop_entry_path }}/localsend.desktop"
      url: https://github.com/localsend/localsend/releases/download/v1.17.0/LocalSend-1.17.0-linux-x86-64.AppImage

    obsidian:
      name: Obsidian
      appimage_path: "{{ package_management.appimage_path }}/Obsidian.AppImage"
      desktop_entry_path: "{{ package_management.desktop_entry_path }}/obsidian.desktop"
      url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.10.6/Obsidian-1.10.6.AppImage

package_management:
  appimage_path: "{{ ansible_facts['env']['HOME'] }}/.local/bin"
  desktop_entry_path: "{{ ansible_facts['env']['HOME'] }}/.local/share/applications"

terminals:
  - alacritty

workspace:
  path: $HOME/workspace/github.com/jameskaupert
