---
- name: Set up workspace folder
  ansible.builtin.file:
    path: "{{ workspace.path }}"
    state: directory

- name: Git - Set user.email
  community.general.git_config:
    name: user.email
    value: "{{ personal.git_email }}"
    scope: global

- name: Git - Set user.name
  community.general.git_config:
    name: user.name
    value: "{{ personal.git_name }}"
    scope: global

- name: Add user to service-restart group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: service-restart
    append: true
