---
- name: Install audio packages from Pacman
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ audio.packages }}"
    state: present

- name: Start and Enable Bluetooth
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: bluetooth
    state: started
    enabled: true
