---
- name: Install terminals from Pacman
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ terminals.packages }}"
    state: present

- name: Create Alacritty default config path
  become: true
  become_user: root
  file:
    path: /etc/alacritty
    recurse: true
    state: directory
    mode: '0755'

- name: Install Alacritty default config
  become: true
  become_user: root
  copy:
    src: alacritty.toml
    dest: /etc/alacritty
    mode: '0644'
